POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZWFlMDk2OTg3ZDY5ZjBiZTA0ZDU5YyIsInVzZXJuYW1lIjoibWlkdWRldiIsImlhdCI6MTY1OTgwOTk1MSwiZXhwIjoxNjYwNDE0NzUxfQ.Di45LoOXYKgNZx6Rj-Jkt9tmjTxEVGm1UCGeLJhiT6g

{
    "content": "Utilizando el middleware del user extractor",
    "important": true
}